DROP TABLE IF EXISTS order_dishes CASCADE;

CREATE TABLE order_dishes (
  id SERIAL PRIMARY KEY NOT NULL,
  order_id INTEGER REFERENCES orders(id) ON DELETE CASCADE,
  dish_id INTEGER REFERENCES dishes(id) ON DELETE CASCADE,
  quantity SMALLINT NOT NULL DEFAULT 1
);
